# Project 1 CMSC 320
##David Morin
##116539265

Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - beautifulsoup4


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    beautifulsoup4-4.10.0      |     pyha770c72_0          77 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          77 KB

The following packages will be UPDATED:

  beautifulsoup4                         4.9.3-pyhb0f4dca_0 --> 4.10.0-pyha770c72_0



Downloading and Extracting Packages
beautifulsoup4-4.10. | 77 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

Collecting package metadata (current_repodata.json): done
Solving environment: \ ^C
|
Note: you may need to restart the kernel to use updated packages.

Collecting package metadata (current_repodata.json): done
Solving environment: \ ^C
failed with initial frozen solve. Retrying with flexible solve.

CondaError: KeyboardInterrupt

KeyboardInterrupt:

In [72]:
from bs4 import BeautifulSoup
import requests
import datetime
import numpy as np
import pandas as pd

Installing and importing required Python packages

# Part 1 Step 1

In [73]:
url = 'https://cmsc320.github.io/files/top-50-solar-flares.html'
r = requests.get(url)

Using requests to get the url

In [74]:
soup = BeautifulSoup(r.content)
new_table = soup.find("table")

Using BeautifulSoup to read and parse the data. Then, I utilize the find() function to save the data table
as a variable.

In [75]:
df = pd.read_html(str(new_table))[0]
df.columns = ['rank', 'x_classification', 'date', 'region', 'start_time', 'maximum_time', 'end_time', 'movie']

Read in the table with Pandas and save it a dataframe with properly named columns

In [76]:
df

,rank,x_classification,date,region,start_time,maximum_time,end_time,movie
0,1,X28+,2003/11/04,486,19:29,19:53,20:06,MovieView archive
1,2,X20+,2001/04/02,9393,21:32,21:51,22:03,MovieView archive
2,3,X17.2+,2003/10/28,486,09:51,11:10,11:24,MovieView archive
3,4,X17+,2005/09/07,808,17:17,17:40,18:03,MovieView archive
4,5,X14.4,2001/04/15,9415,13:19,13:50,13:55,MovieView archive
5,6,X10,2003/10/29,486,20:37,20:49,21:01,MovieView archive
6,7,X9.4,1997/11/06,8100,11:49,11:55,12:01,MovieView archive
7,8,X9.3,2017/09/06,2673,11:53,12:02,12:10,MovieView archive
8,9,X9,2006/12/05,930,10:18,10:35,10:45,MovieView archive
9,10,X8.3,2003/11/02,486,17:03,17:25,17:39,MovieView archive
10,11,X8.2,2017/09/10,2673,15:35,16:06,16:31,MovieView archive
11,12,X7.1,2005/01/20,720,06:36,07:01,07:26,MovieView archive
12,13,X6.9,2011/08/09,1263,07:48,08:05,08:08,MovieView archive
13,14,X6.5,2006/12/06,930,18:29,18:47,19:00,MovieView archive
14,15,X6.2,2005/09/09,808,19:13,20:04,20:36,MovieView archive
15,16,X6.2,2001/12/13,9733,14:20,14:30,14:35,MovieView archive
16,17,X5.7,2000/07/14,9077,10:03,10:24,10:43,MovieView archive
17,18,X5.6,2001/04/06,9415,19:10,19:21,19:31,MovieView archive
18,19,X5.4,2012/03/07,1429,00:02,00:24,00:40,MovieView archive
19,20,X5.4,2005/09/08,808,20:52,21:06,21:17,MovieView archive
20,21,X5.4,2003/10/23,486,08:19,08:35,08:49,MovieView archive
21,22,X5.3,2001/08/25,9591,16:23,16:45,17:04,MovieView archive
22,23,X4.9,2014/02/25,1990,00:39,00:49,01:03,MovieView archive
23,24,X4.9,1998/08/18,8307,22:10,22:19,22:28,View archive
24,25,X4.8,2002/07/23,39,00:18,00:35,00:47,MovieView archive
25,26,X4,2000/11/26,9236,16:34,16:48,16:56,MovieView archive
26,27,X3.9,2003/11/03,488,09:43,09:55,10:19,MovieView archive
27,28,X3.9,1998/08/19,8307,21:35,21:45,21:50,View archive
28,29,X3.8,2005/01/17,720,06:59,09:52,10:07,MovieView archive
29,30,X3.7,1998/11/22,8384,06:30,06:42,06:49,MovieView archive
30,31,X3.6,2005/09/09,808,09:42,09:59,10:08,MovieView archive
31,32,X3.6,2004/07/16,649,13:49,13:55,14:01,MovieView archive
32,33,X3.6,2003/05/28,365,00:17,00:27,00:39,MovieView archive
33,34,X3.4,2006/12/13,930,02:14,02:40,02:57,MovieView archive
34,35,X3.4,2001/12/28,9767,20:02,20:45,21:32,MovieView archive
35,36,X3.3,2013/11/05,1890,22:07,22:12,22:15,MovieView archive
36,37,X3.3,2002/07/20,39,21:04,21:30,21:54,MovieView archive
37,38,X3.3,1998/11/28,8395,04:54,05:52,06:13,MovieView archive
38,39,X3.2,2013/05/14,1748,00:00,01:11,01:20,MovieView archive
39,40,X3.1,2014/10/24,2192,21:07,21:41,22:13,MovieView archive
40,41,X3.1,2002/08/24,69,00:49,01:12,01:31,MovieView archive
41,42,X3,2002/07/15,30,19:59,20:08,20:14,MovieView archive
42,43,X2.8,2013/05/13,1748,15:48,16:05,16:16,MovieView archive
43,44,X2.8,2001/12/11,9733,07:58,08:08,08:14,MovieView archive
44,45,X2.8,1998/08/18,8307,08:14,08:24,08:32,View archive
45,46,X2.7,2015/05/05,2339,22:05,22:11,22:15,MovieView archive
46,47,X2.7,2003/11/03,488,01:09,01:30,01:45,MovieView archive
47,48,X2.7,1998/05/06,8210,07:58,08:09,08:20,MovieView archive
48,49,X2.6,2005/01/15,720,22:25,23:02,23:31,MovieView archive
49,50,X2.6,2001/09/24,9632,09:32,10:38,11:09,MovieView archive

# Part 1 Step 2

In [77]:
df = df.drop('movie', axis = 1)

Drop the movie column as it is unneccesary to our analysis

In [78]:
df['date'] = df['date'].astype(str)
df['start_time'] = df['start_time'].astype(str)
df['maximum_time'] = df['maximum_time'].astype(str)
df['end_time'] = df['end_time'].astype(str)

Converting the types to Strings to avoid type errors when creating the datetime columns

In [79]:
c1 = pd.to_datetime(df['date'] + ' ' + df['start_time'])
c2 = pd.to_datetime(df['date'] + ' ' + df['maximum_time'])
c3 = pd.to_datetime(df['date'] + ' ' + df['end_time'])

df['start_datetime'] = c1
df['maximum_datetime'] = c2
df['end_datetime'] = c3

Creating the datetime columns

In [80]:
df = df.drop('start_time', axis = 1)
df = df.drop('maximum_time', axis = 1)
df = df.drop('end_time', axis = 1)
df = df.drop('date', axis=1)

df

,rank,x_classification,region,start_datetime,maximum_datetime,end_datetime
0,1,X28+,486,2003-11-04 19:29:00,2003-11-04 19:53:00,2003-11-04 20:06:00
1,2,X20+,9393,2001-04-02 21:32:00,2001-04-02 21:51:00,2001-04-02 22:03:00
2,3,X17.2+,486,2003-10-28 09:51:00,2003-10-28 11:10:00,2003-10-28 11:24:00
3,4,X17+,808,2005-09-07 17:17:00,2005-09-07 17:40:00,2005-09-07 18:03:00
4,5,X14.4,9415,2001-04-15 13:19:00,2001-04-15 13:50:00,2001-04-15 13:55:00
5,6,X10,486,2003-10-29 20:37:00,2003-10-29 20:49:00,2003-10-29 21:01:00
6,7,X9.4,8100,1997-11-06 11:49:00,1997-11-06 11:55:00,1997-11-06 12:01:00
7,8,X9.3,2673,2017-09-06 11:53:00,2017-09-06 12:02:00,2017-09-06 12:10:00
8,9,X9,930,2006-12-05 10:18:00,2006-12-05 10:35:00,2006-12-05 10:45:00
9,10,X8.3,486,2003-11-02 17:03:00,2003-11-02 17:25:00,2003-11-02 17:39:00
10,11,X8.2,2673,2017-09-10 15:35:00,2017-09-10 16:06:00,2017-09-10 16:31:00
11,12,X7.1,720,2005-01-20 06:36:00,2005-01-20 07:01:00,2005-01-20 07:26:00
12,13,X6.9,1263,2011-08-09 07:48:00,2011-08-09 08:05:00,2011-08-09 08:08:00
13,14,X6.5,930,2006-12-06 18:29:00,2006-12-06 18:47:00,2006-12-06 19:00:00
14,15,X6.2,808,2005-09-09 19:13:00,2005-09-09 20:04:00,2005-09-09 20:36:00
15,16,X6.2,9733,2001-12-13 14:20:00,2001-12-13 14:30:00,2001-12-13 14:35:00
16,17,X5.7,9077,2000-07-14 10:03:00,2000-07-14 10:24:00,2000-07-14 10:43:00
17,18,X5.6,9415,2001-04-06 19:10:00,2001-04-06 19:21:00,2001-04-06 19:31:00
18,19,X5.4,1429,2012-03-07 00:02:00,2012-03-07 00:24:00,2012-03-07 00:40:00
19,20,X5.4,808,2005-09-08 20:52:00,2005-09-08 21:06:00,2005-09-08 21:17:00
20,21,X5.4,486,2003-10-23 08:19:00,2003-10-23 08:35:00,2003-10-23 08:49:00
21,22,X5.3,9591,2001-08-25 16:23:00,2001-08-25 16:45:00,2001-08-25 17:04:00
22,23,X4.9,1990,2014-02-25 00:39:00,2014-02-25 00:49:00,2014-02-25 01:03:00
23,24,X4.9,8307,1998-08-18 22:10:00,1998-08-18 22:19:00,1998-08-18 22:28:00
24,25,X4.8,39,2002-07-23 00:18:00,2002-07-23 00:35:00,2002-07-23 00:47:00
25,26,X4,9236,2000-11-26 16:34:00,2000-11-26 16:48:00,2000-11-26 16:56:00
26,27,X3.9,488,2003-11-03 09:43:00,2003-11-03 09:55:00,2003-11-03 10:19:00
27,28,X3.9,8307,1998-08-19 21:35:00,1998-08-19 21:45:00,1998-08-19 21:50:00
28,29,X3.8,720,2005-01-17 06:59:00,2005-01-17 09:52:00,2005-01-17 10:07:00
29,30,X3.7,8384,1998-11-22 06:30:00,1998-11-22 06:42:00,1998-11-22 06:49:00
30,31,X3.6,808,2005-09-09 09:42:00,2005-09-09 09:59:00,2005-09-09 10:08:00
31,32,X3.6,649,2004-07-16 13:49:00,2004-07-16 13:55:00,2004-07-16 14:01:00
32,33,X3.6,365,2003-05-28 00:17:00,2003-05-28 00:27:00,2003-05-28 00:39:00
33,34,X3.4,930,2006-12-13 02:14:00,2006-12-13 02:40:00,2006-12-13 02:57:00
34,35,X3.4,9767,2001-12-28 20:02:00,2001-12-28 20:45:00,2001-12-28 21:32:00
35,36,X3.3,1890,2013-11-05 22:07:00,2013-11-05 22:12:00,2013-11-05 22:15:00
36,37,X3.3,39,2002-07-20 21:04:00,2002-07-20 21:30:00,2002-07-20 21:54:00
37,38,X3.3,8395,1998-11-28 04:54:00,1998-11-28 05:52:00,1998-11-28 06:13:00
38,39,X3.2,1748,2013-05-14 00:00:00,2013-05-14 01:11:00,2013-05-14 01:20:00
39,40,X3.1,2192,2014-10-24 21:07:00,2014-10-24 21:41:00,2014-10-24 22:13:00
40,41,X3.1,69,2002-08-24 00:49:00,2002-08-24 01:12:00,2002-08-24 01:31:00
41,42,X3,30,2002-07-15 19:59:00,2002-07-15 20:08:00,2002-07-15 20:14:00
42,43,X2.8,1748,2013-05-13 15:48:00,2013-05-13 16:05:00,2013-05-13 16:16:00
43,44,X2.8,9733,2001-12-11 07:58:00,2001-12-11 08:08:00,2001-12-11 08:14:00
44,45,X2.8,8307,1998-08-18 08:14:00,1998-08-18 08:24:00,1998-08-18 08:32:00
45,46,X2.7,2339,2015-05-05 22:05:00,2015-05-05 22:11:00,2015-05-05 22:15:00
46,47,X2.7,488,2003-11-03 01:09:00,2003-11-03 01:30:00,2003-11-03 01:45:00
47,48,X2.7,8210,1998-05-06 07:58:00,1998-05-06 08:09:00,1998-05-06 08:20:00
48,49,X2.6,720,2005-01-15 22:25:00,2005-01-15 23:02:00,2005-01-15 23:31:00
49,50,X2.6,9632,2001-09-24 09:32:00,2001-09-24 10:38:00,2001-09-24 11:09:00

In [81]:
df = df.replace(to_replace='-', value=np.nan)

Drop all of the unnecessary columns and replace any missing values to NaN

In [82]:
df

,rank,x_classification,region,start_datetime,maximum_datetime,end_datetime
0,1,X28+,486,2003-11-04 19:29:00,2003-11-04 19:53:00,2003-11-04 20:06:00
1,2,X20+,9393,2001-04-02 21:32:00,2001-04-02 21:51:00,2001-04-02 22:03:00
2,3,X17.2+,486,2003-10-28 09:51:00,2003-10-28 11:10:00,2003-10-28 11:24:00
3,4,X17+,808,2005-09-07 17:17:00,2005-09-07 17:40:00,2005-09-07 18:03:00
4,5,X14.4,9415,2001-04-15 13:19:00,2001-04-15 13:50:00,2001-04-15 13:55:00
5,6,X10,486,2003-10-29 20:37:00,2003-10-29 20:49:00,2003-10-29 21:01:00
6,7,X9.4,8100,1997-11-06 11:49:00,1997-11-06 11:55:00,1997-11-06 12:01:00
7,8,X9.3,2673,2017-09-06 11:53:00,2017-09-06 12:02:00,2017-09-06 12:10:00
8,9,X9,930,2006-12-05 10:18:00,2006-12-05 10:35:00,2006-12-05 10:45:00
9,10,X8.3,486,2003-11-02 17:03:00,2003-11-02 17:25:00,2003-11-02 17:39:00
10,11,X8.2,2673,2017-09-10 15:35:00,2017-09-10 16:06:00,2017-09-10 16:31:00
11,12,X7.1,720,2005-01-20 06:36:00,2005-01-20 07:01:00,2005-01-20 07:26:00
12,13,X6.9,1263,2011-08-09 07:48:00,2011-08-09 08:05:00,2011-08-09 08:08:00
13,14,X6.5,930,2006-12-06 18:29:00,2006-12-06 18:47:00,2006-12-06 19:00:00
14,15,X6.2,808,2005-09-09 19:13:00,2005-09-09 20:04:00,2005-09-09 20:36:00
15,16,X6.2,9733,2001-12-13 14:20:00,2001-12-13 14:30:00,2001-12-13 14:35:00
16,17,X5.7,9077,2000-07-14 10:03:00,2000-07-14 10:24:00,2000-07-14 10:43:00
17,18,X5.6,9415,2001-04-06 19:10:00,2001-04-06 19:21:00,2001-04-06 19:31:00
18,19,X5.4,1429,2012-03-07 00:02:00,2012-03-07 00:24:00,2012-03-07 00:40:00
19,20,X5.4,808,2005-09-08 20:52:00,2005-09-08 21:06:00,2005-09-08 21:17:00
20,21,X5.4,486,2003-10-23 08:19:00,2003-10-23 08:35:00,2003-10-23 08:49:00
21,22,X5.3,9591,2001-08-25 16:23:00,2001-08-25 16:45:00,2001-08-25 17:04:00
22,23,X4.9,1990,2014-02-25 00:39:00,2014-02-25 00:49:00,2014-02-25 01:03:00
23,24,X4.9,8307,1998-08-18 22:10:00,1998-08-18 22:19:00,1998-08-18 22:28:00
24,25,X4.8,39,2002-07-23 00:18:00,2002-07-23 00:35:00,2002-07-23 00:47:00
25,26,X4,9236,2000-11-26 16:34:00,2000-11-26 16:48:00,2000-11-26 16:56:00
26,27,X3.9,488,2003-11-03 09:43:00,2003-11-03 09:55:00,2003-11-03 10:19:00
27,28,X3.9,8307,1998-08-19 21:35:00,1998-08-19 21:45:00,1998-08-19 21:50:00
28,29,X3.8,720,2005-01-17 06:59:00,2005-01-17 09:52:00,2005-01-17 10:07:00
29,30,X3.7,8384,1998-11-22 06:30:00,1998-11-22 06:42:00,1998-11-22 06:49:00
30,31,X3.6,808,2005-09-09 09:42:00,2005-09-09 09:59:00,2005-09-09 10:08:00
31,32,X3.6,649,2004-07-16 13:49:00,2004-07-16 13:55:00,2004-07-16 14:01:00
32,33,X3.6,365,2003-05-28 00:17:00,2003-05-28 00:27:00,2003-05-28 00:39:00
33,34,X3.4,930,2006-12-13 02:14:00,2006-12-13 02:40:00,2006-12-13 02:57:00
34,35,X3.4,9767,2001-12-28 20:02:00,2001-12-28 20:45:00,2001-12-28 21:32:00
35,36,X3.3,1890,2013-11-05 22:07:00,2013-11-05 22:12:00,2013-11-05 22:15:00
36,37,X3.3,39,2002-07-20 21:04:00,2002-07-20 21:30:00,2002-07-20 21:54:00
37,38,X3.3,8395,1998-11-28 04:54:00,1998-11-28 05:52:00,1998-11-28 06:13:00
38,39,X3.2,1748,2013-05-14 00:00:00,2013-05-14 01:11:00,2013-05-14 01:20:00
39,40,X3.1,2192,2014-10-24 21:07:00,2014-10-24 21:41:00,2014-10-24 22:13:00
40,41,X3.1,69,2002-08-24 00:49:00,2002-08-24 01:12:00,2002-08-24 01:31:00
41,42,X3,30,2002-07-15 19:59:00,2002-07-15 20:08:00,2002-07-15 20:14:00
42,43,X2.8,1748,2013-05-13 15:48:00,2013-05-13 16:05:00,2013-05-13 16:16:00
43,44,X2.8,9733,2001-12-11 07:58:00,2001-12-11 08:08:00,2001-12-11 08:14:00
44,45,X2.8,8307,1998-08-18 08:14:00,1998-08-18 08:24:00,1998-08-18 08:32:00
45,46,X2.7,2339,2015-05-05 22:05:00,2015-05-05 22:11:00,2015-05-05 22:15:00
46,47,X2.7,488,2003-11-03 01:09:00,2003-11-03 01:30:00,2003-11-03 01:45:00
47,48,X2.7,8210,1998-05-06 07:58:00,1998-05-06 08:09:00,1998-05-06 08:20:00
48,49,X2.6,720,2005-01-15 22:25:00,2005-01-15 23:02:00,2005-01-15 23:31:00
49,50,X2.6,9632,2001-09-24 09:32:00,2001-09-24 10:38:00,2001-09-24 11:09:00

# Part 1 Step 3

In [83]:
url = 'http://www.hcbravo.org/IntroDataSci/misc/waves_type2.html'
nr = requests.get(url)

In [84]:
text = nr.text
root = BeautifulSoup(text, 'lxml')
new_text = root.text

Use requests to get the URL then use BeautifulSoup to extract the text

In [85]:
lines = new_text.splitlines()[15:496]
nasa_df = pd.DataFrame(lines)

nasa_df = nasa_df[0].str.split(n=15, expand=True)

Getting the text line by line then creating a DataFrame to hold the table. Then, I separate the whitespace
into 15 columns.

In [86]:
nasa_df.drop(15, axis=1, inplace=True)
nasa_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1997/04/01,14:00,04/01,14:15,8000,4000,S25E16,8026,M1.3,04/01,15:18,74,79,312,PHTX
1,1997/04/07,14:30,04/07,17:30,11000,1000,S28E19,8027,C6.8,04/07,14:27,Halo,360,878,PHTX
2,1997/05/12,05:15,05/14,16:00,12000,80,N21W08,8038,C1.3,05/12,05:30,Halo,360,464,PHTX
3,1997/05/21,20:20,05/21,22:00,5000,500,N05W12,8040,M1.3,05/21,21:00,263,165,296,PHTX
4,1997/09/23,21:53,09/23,22:16,6000,2000,S29E25,8088,C1.4,09/23,22:02,133,155,712,PHTX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,2014/11/08,16:57,11/08,17:18,14000,7800,W90b,12203,----,11/08,16:36,305,141,426,PHTX
477,2014/12/13,14:27,12/13,14:51,14000,3900,W90b,-----,----,12/13,14:24,Halo,360,2222,PHTX
478,2014/12/17,04:09,12/17,04:19,2900,2100,S11E33,12241,M1.1,12/17,02:00,107,108,869,PHTX
479,2014/12/17,05:00,12/17,05:09,14000,11500,S20E09,12242,M8.7,12/17,05:00,Halo,360,587,PHTX
480,2014/12/18,22:31,12/18,22:54,5100,1300,S11E15,12241,M6.9,12/19,01:04,Halo,360,1195,PHTX

Drop the last table as the data is unnecessary to analysis.

In [87]:
nasa_df.rename(columns={0: "start_date", 1:'start_time', 2: 'end_date', 3: 'end_time', 4: 'start_frequency',\
                        5: 'end_frequency',6: 'flare_location', 7: 'flare_region', 8: 'flare_classification',\
                        9: 'cme_date', 10: 'cme_time', 11: 'cme_angle', 12: 'cme_width', 13: 'cme_speed', \
                       14: 'proton'}, inplace=True)

Rename the columns to detailed names.

In [88]:
nasa_df

,start_date,start_time,end_date,end_time,start_frequency,end_frequency,flare_location,flare_region,flare_classification,cme_date,cme_time,cme_angle,cme_width,cme_speed,proton
0,1997/04/01,14:00,04/01,14:15,8000,4000,S25E16,8026,M1.3,04/01,15:18,74,79,312,PHTX
1,1997/04/07,14:30,04/07,17:30,11000,1000,S28E19,8027,C6.8,04/07,14:27,Halo,360,878,PHTX
2,1997/05/12,05:15,05/14,16:00,12000,80,N21W08,8038,C1.3,05/12,05:30,Halo,360,464,PHTX
3,1997/05/21,20:20,05/21,22:00,5000,500,N05W12,8040,M1.3,05/21,21:00,263,165,296,PHTX
4,1997/09/23,21:53,09/23,22:16,6000,2000,S29E25,8088,C1.4,09/23,22:02,133,155,712,PHTX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,2014/11/08,16:57,11/08,17:18,14000,7800,W90b,12203,----,11/08,16:36,305,141,426,PHTX
477,2014/12/13,14:27,12/13,14:51,14000,3900,W90b,-----,----,12/13,14:24,Halo,360,2222,PHTX
478,2014/12/17,04:09,12/17,04:19,2900,2100,S11E33,12241,M1.1,12/17,02:00,107,108,869,PHTX
479,2014/12/17,05:00,12/17,05:09,14000,11500,S20E09,12242,M8.7,12/17,05:00,Halo,360,587,PHTX
480,2014/12/18,22:31,12/18,22:54,5100,1300,S11E15,12241,M6.9,12/19,01:04,Halo,360,1195,PHTX

In [89]:
nasa_df = nasa_df.replace("????", np.nan)
nasa_df = nasa_df.replace("---", np.nan)
nasa_df = nasa_df.replace("----", np.nan)
nasa_df = nasa_df.replace("-----", np.nan)
nasa_df = nasa_df.replace("--:--", np.nan)
nasa_df = nasa_df.replace("--/--", np.nan)

Replace all the missing values in the table NaN

In [90]:
new_col = nasa_df['cme_angle'] == 'Halo'
nasa_df['halo'] = new_col
nasa_df['cme_angle'] = nasa_df['cme_angle'].replace('Halo', np.nan)

Creating new column 'halo' to check if the solar flare is a halo. Replaces the 'Halo' with NaN in 'cme_angle'
as it is no longer needed.

In [91]:
width = list(map(lambda x: str(x).startswith('>'), nasa_df['cme_width']))
nasa_df['is_lower_bound'] = width

In [92]:
nasa_df['cme_width'] = list(map(lambda x: float(x[1:]) if str(x).startswith('>') else x, nasa_df["cme_width"]))

Using map to create a boolean column called 'is_lower_bound' which says if the width is lower bounded. Then,I use map again to remove the '>' from 'cme_width' column

In [93]:
nasa_df["start_datetime"] = pd.to_datetime(nasa_df["start_date"] + ' ' + nasa_df['start_time']) 
nasa_df["end_datetime"] = pd.to_datetime(nasa_df["end_date"] + ' ' + nasa_df['end_time'], errors='ignore') 
nasa_df["cme_datetime"] = pd.to_datetime(nasa_df["cme_date"] + ' ' + nasa_df['cme_time'], errors='ignore') 


nasa_df = nasa_df.drop("start_date", axis = 1)
nasa_df = nasa_df.drop("start_time", axis = 1)
nasa_df = nasa_df.drop("end_date", axis = 1)
nasa_df = nasa_df.drop("end_time", axis = 1)
nasa_df = nasa_df.drop("cme_date", axis = 1)
nasa_df = nasa_df.drop("cme_time", axis = 1)

Creating datime columns and dropping the unnecesarry ones from the table.

In [94]:
nasa_df

,start_frequency,end_frequency,flare_location,flare_region,flare_classification,cme_angle,cme_width,cme_speed,proton,halo,is_lower_bound,start_datetime,end_datetime,cme_datetime
0,8000,4000,S25E16,8026,M1.3,74,79,312,PHTX,False,False,1997-04-01 14:00:00,04/01 14:15,04/01 15:18
1,11000,1000,S28E19,8027,C6.8,NaN,360,878,PHTX,True,False,1997-04-07 14:30:00,04/07 17:30,04/07 14:27
2,12000,80,N21W08,8038,C1.3,NaN,360,464,PHTX,True,False,1997-05-12 05:15:00,05/14 16:00,05/12 05:30
3,5000,500,N05W12,8040,M1.3,263,165,296,PHTX,False,False,1997-05-21 20:20:00,05/21 22:00,05/21 21:00
4,6000,2000,S29E25,8088,C1.4,133,155,712,PHTX,False,False,1997-09-23 21:53:00,09/23 22:16,09/23 22:02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,14000,7800,W90b,12203,NaN,305,141,426,PHTX,False,False,2014-11-08 16:57:00,11/08 17:18,11/08 16:36
477,14000,3900,W90b,NaN,NaN,NaN,360,2222,PHTX,True,False,2014-12-13 14:27:00,12/13 14:51,12/13 14:24
478,2900,2100,S11E33,12241,M1.1,107,108,869,PHTX,False,False,2014-12-17 04:09:00,12/17 04:19,12/17 02:00
479,14000,11500,S20E09,12242,M8.7,NaN,360,587,PHTX,True,False,2014-12-17 05:00:00,12/17 05:09,12/17 05:00
480,5100,1300,S11E15,12241,M6.9,NaN,360,1195,PHTX,True,False,2014-12-18 22:31:00,12/18 22:54,12/19 01:04

# Part 2 Step 1

In [95]:
nasa_df.sort_values(by='flare_classification', ascending=False, inplace=True)
nasa_df.head(50)

,start_frequency,end_frequency,flare_location,flare_region,flare_classification,cme_angle,cme_width,cme_speed,proton,halo,is_lower_bound,start_datetime,end_datetime,cme_datetime
8,14000,100,S18W63,8100,X9.4,NaN,360,1556,PHTX,True,False,1997-11-06 12:20:00,11/07 08:30,11/06 12:10
330,14000,250,S07E68,10930,X9.0,NaN,NaN,NaN,PHTX,False,False,2006-12-05 10:50:00,12/05 20:00,NaN
238,12000,250,S14W56,10486,X8.3,NaN,360,2598,PHTX,True,False,2003-11-02 17:30:00,11/03 01:00,11/02 17:30
290,14000,25,N14W61,10720,X7.1,NaN,360,882,PHTX,True,False,2005-01-20 07:15:00,01/20 16:30,01/20 06:54
360,16000,4000,N17W69,11263,X6.9,NaN,360,1610,PHTX,True,False,2011-08-09 08:20:00,08/09 08:35,08/09 08:12
333,16000,30,S05E64,10930,X6.5,NaN,NaN,NaN,PHTX,False,False,2006-12-06 19:00:00,12/08 24:00,NaN
319,10000,50,S12E67,10808,X6.2,NaN,360,2257,PHTX,True,False,2005-09-09 19:45:00,09/09 22:00,09/09 19:48
83,14000,80,N22W07,9077,X5.7,NaN,360,1674,PHTX,True,False,2000-07-14 10:30:00,07/15 14:30,07/14 10:54
123,14000,230,S21E31,9415,X5.6,NaN,360,1270,PHTX,True,False,2001-04-06 19:35:00,04/07 01:50,04/06 19:30
376,16000,30,N17E27,11429,X5.4,NaN,360,2684,PHTX,True,False,2012-03-07 01:00:00,03/08 19:00,03/07 00:24
137,8000,170,S17E34,9591,X5.3,NaN,360,1433,PHTX,True,False,2001-08-25 16:50:00,08/25 23:00,08/25 16:50
444,14000,100,S13E82,11990,X4.9,NaN,360,2147,PHTX,True,False,2014-02-25 00:56:00,02/25 11:28,02/25 01:25
195,11000,400,S13E72,10039,X4.8,NaN,360,2285,PHTX,True,False,2002-07-23 00:50:00,07/23 04:00,07/23 00:42
106,14000,7000,N18W38,9236,X4.0,NaN,360,980,PHTX,True,False,2000-11-26 17:00:00,11/26 17:15,11/26 17:06
240,6000,400,N08W77,10488,X3.9,293,103,1420,PHTX,False,False,2003-11-03 10:00:00,11/03 12:30,11/03 10:06
289,6100,1500,N15W25,10720,X3.8,NaN,360,2547,PHTX,True,False,2005-01-17 10:00:00,01/17 10:35,01/17 09:54
223,1000,200,S06W21,10365,X3.6,NaN,360,1366,PHTX,True,False,2003-05-28 01:00:00,05/29 00:30,05/28 00:50
162,14000,350,S26E90,9756,X3.4,NaN,360,2216,PHTX,True,False,2001-12-28 20:35:00,12/29 03:00,12/28 20:30
334,12000,150,S06W23,10930,X3.4,NaN,360,1774,PHTX,True,False,2006-12-13 02:45:00,12/13 10:40,12/13 02:54
194,10000,2000,SE90b,10039,X3.3,NaN,360,1941,PHTX,True,False,2002-07-20 21:30:00,07/20 22:20,07/20 22:06
405,16000,700,N08E77,11748,X3.2,NaN,360,2625,PHTX,True,False,2013-05-14 01:16:00,05/14 02:35,05/14 01:25
202,5000,400,S02W81,10069,X3.1,NaN,360,1913,PHTX,True,False,2002-08-24 01:45:00,08/24 03:25,08/24 01:27
242,10000,200,S19W83,10486,X28.,NaN,360,2657,PHTX,True,False,2003-11-04 20:00:00,11/04 24:00,11/04 19:54
119,14000,250,N19W72,9393,X20.,261,244,2505,PHTX,False,False,2001-04-02 22:05:00,04/03 02:30,04/02 22:06
404,16000,300,N11E85,11748,X2.8,NaN,360,1850,PHTX,True,False,2013-05-13 16:15:00,05/13 19:10,05/13 16:07
19,14000,5000,S11W65,8210,X2.7,309,190,1099,PHTX,False,False,1998-05-06 08:25:00,05/06 08:35,05/06 08:29
239,3000,1500,N10W83,10488,X2.7,304,65,827,PHTX,False,False,2003-11-03 01:15:00,11/03 01:25,11/03 01:59
286,3000,40,N15W05,10720,X2.6,NaN,360,2861,PHTX,True,False,2005-01-15 23:00:00,01/15 00:00,01/15 23:06
144,7000,30,S16E23,9632,X2.6,NaN,360,2402,PHTX,True,False,2001-09-24 10:45:00,09/25 20:00,09/24 10:30
9,14000,7000,N17E63,8113,X2.6,98,91,441,PHTX,False,False,1997-11-27 13:30:00,11/27 14:00,11/27 13:56
278,14000,1000,N09W49,10696,X2.5,NaN,360,3387,PHTX,True,False,2004-11-10 02:25:00,11/10 03:40,11/10 02:26
101,14000,200,N22W07,9236,X2.3,NaN,360,1245,PHTX,True,False,2000-11-24 15:25:00,11/24 22:00,11/24 15:30
125,14000,100,S23W09,9415,X2.3,NaN,360,2411,PHTX,True,False,2001-04-10 05:24:00,04/10 24:00,04/10 05:30
73,14000,40,N20E18,9026,X2.3,NaN,360,1119,PHTX,True,False,2000-06-06 15:20:00,06/08 09:00,06/06 15:54
347,16000,400,S20W12,11158,X2.2,NaN,360,669,PHTX,True,False,2011-02-15 02:10:00,02/15 07:00,02/15 02:24
421,16000,200,S06E69,11882,X2.1,NaN,360,1081,PHTX,True,False,2013-10-25 15:08:00,10/25 22:32,10/25 15:12
362,16000,150,N14W18,11283,X2.1,NaN,360,575,PHTX,True,False,2011-09-06 22:30:00,09/07 15:40,09/06 23:05
7,14000,100,S14W33,8100,X2.1,NaN,360,785,PHTX,True,False,1997-11-04 06:00:00,11/05 04:30,11/04 06:10
320,14000,300,S13E47,10808,X2.1,NaN,360,1893,PHTX,True,False,2005-09-10 21:45:00,09/10 01:00,09/10 21:52
287,14000,30,N15W25,10720,X2.0,NaN,360,2094,PHTX,True,False,2005-01-17 09:25:00,01/17 16:00,01/17 09:30
127,14000,7000,S19W43,9415,X2.0,NaN,360,1184,PHTX,True,False,2001-04-12 10:20:00,04/12 10:40,04/12 10:31
276,14000,60,N09W17,10696,X2.0,NaN,360,1759,PHTX,True,False,2004-11-07 16:25:00,11/08 20:00,11/07 16:54
100,14000,100,N20W05,9236,X2.0,NaN,360,1289,PHTX,True,False,2000-11-24 05:10:00,11/24 15:00,11/24 05:30
234,14000,40,S16E08,10486,X17.,NaN,360,2459,PHTX,True,False,2003-10-28 11:10:00,10/29 24:00,10/28 11:30
128,14000,40,S20W85,9415,X14.,245,167,1199,PHTX,False,False,2001-04-15 14:05:00,04/16 13:00,04/15 14:06
235,11000,500,S15W02,10486,X10.,NaN,360,2029,PHTX,True,False,2003-10-29 20:55:00,10/29 24:00,10/29 20:54
104,6000,2000,N20W23,9236,X1.9,NaN,360,671,PHTX,True,False,2000-11-25 19:00:00,11/25 19:35,11/25 19:31
49,14000,4000,N11E32,8731,X1.8,NaN,360,1250,PHTX,True,False,1999-10-14 09:10:00,10/14 10:00,10/14 09:26
191,14000,1500,N19W30,10030,X1.8,NaN,360,1099,PHTX,True,False,2002-07-18 07:55:00,07/18 08:45,07/18 08:06
102,4000,3000,N21W14,9236,X1.8,NaN,360,1005,PHTX,True,False,2000-11-24 22:24:00,11/24 22:36,11/24 22:06

I got the top 50 flares as it is in the previous database, but the ordering is different because the format of the data is not the same.

# Part 2 Step 2

In [98]:
nasa_df['rank'] = np.nan

for index, row in df.iterrows():
    final = nasa_df.loc[(nasa_df["start_datetime"].dt.year == row["start_datetime"].year)\
                                & (nasa_df["start_datetime"].dt.month == row["start_datetime"].month) & \
                                (nasa_df["start_datetime"].dt.day == row["start_datetime"].day)]
    if not final.empty:
        cur = final.index[0]
        nasa_df['rank'][cur] = row['rank']

nasa_df.sort_values(by='rank', ascending=True, inplace=True)
nasa_df.head(50)

<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']
<ipython-input-98-f2a8cb599251>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasa_df['rank'][cur] = row['rank']

,start_frequency,end_frequency,flare_location,flare_region,flare_classification,cme_angle,cme_width,cme_speed,proton,halo,is_lower_bound,start_datetime,end_datetime,cme_datetime,rank
242,10000,200,S19W83,10486,X28.,NaN,360,2657,PHTX,True,False,2003-11-04 20:00:00,11/04 24:00,11/04 19:54,1.0
119,14000,250,N19W72,9393,X20.,261,244,2505,PHTX,False,False,2001-04-02 22:05:00,04/03 02:30,04/02 22:06,2.0
234,14000,40,S16E08,10486,X17.,NaN,360,2459,PHTX,True,False,2003-10-28 11:10:00,10/29 24:00,10/28 11:30,3.0
318,12000,200,S11E77,10808,X1.7,NaN,NaN,NaN,PHTX,False,False,2005-09-07 18:05:00,09/08 00:00,NaN,4.0
128,14000,40,S20W85,9415,X14.,245,167,1199,PHTX,False,False,2001-04-15 14:05:00,04/16 13:00,04/15 14:06,5.0
235,11000,500,S15W02,10486,X10.,NaN,360,2029,PHTX,True,False,2003-10-29 20:55:00,10/29 24:00,10/29 20:54,6.0
8,14000,100,S18W63,8100,X9.4,NaN,360,1556,PHTX,True,False,1997-11-06 12:20:00,11/07 08:30,11/06 12:10,7.0
330,14000,250,S07E68,10930,X9.0,NaN,NaN,NaN,PHTX,False,False,2006-12-05 10:50:00,12/05 20:00,NaN,9.0
238,12000,250,S14W56,10486,X8.3,NaN,360,2598,PHTX,True,False,2003-11-02 17:30:00,11/03 01:00,11/02 17:30,10.0
290,14000,25,N14W61,10720,X7.1,NaN,360,882,PHTX,True,False,2005-01-20 07:15:00,01/20 16:30,01/20 06:54,12.0
360,16000,4000,N17W69,11263,X6.9,NaN,360,1610,PHTX,True,False,2011-08-09 08:20:00,08/09 08:35,08/09 08:12,13.0
333,16000,30,S05E64,10930,X6.5,NaN,NaN,NaN,PHTX,False,False,2006-12-06 19:00:00,12/08 24:00,NaN,14.0
83,14000,80,N22W07,9077,X5.7,NaN,360,1674,PHTX,True,False,2000-07-14 10:30:00,07/15 14:30,07/14 10:54,17.0
123,14000,230,S21E31,9415,X5.6,NaN,360,1270,PHTX,True,False,2001-04-06 19:35:00,04/07 01:50,04/06 19:30,18.0
376,16000,30,N17E27,11429,X5.4,NaN,360,2684,PHTX,True,False,2012-03-07 01:00:00,03/08 19:00,03/07 00:24,19.0
137,8000,170,S17E34,9591,X5.3,NaN,360,1433,PHTX,True,False,2001-08-25 16:50:00,08/25 23:00,08/25 16:50,22.0
444,14000,100,S13E82,11990,X4.9,NaN,360,2147,PHTX,True,False,2014-02-25 00:56:00,02/25 11:28,02/25 01:25,23.0
195,11000,400,S13E72,10039,X4.8,NaN,360,2285,PHTX,True,False,2002-07-23 00:50:00,07/23 04:00,07/23 00:42,25.0
106,14000,7000,N18W38,9236,X4.0,NaN,360,980,PHTX,True,False,2000-11-26 17:00:00,11/26 17:15,11/26 17:06,26.0
289,6100,1500,N15W25,10720,X3.8,NaN,360,2547,PHTX,True,False,2005-01-17 10:00:00,01/17 10:35,01/17 09:54,29.0
319,10000,50,S12E67,10808,X6.2,NaN,360,2257,PHTX,True,False,2005-09-09 19:45:00,09/09 22:00,09/09 19:48,31.0
223,1000,200,S06W21,10365,X3.6,NaN,360,1366,PHTX,True,False,2003-05-28 01:00:00,05/29 00:30,05/28 00:50,33.0
334,12000,150,S06W23,10930,X3.4,NaN,360,1774,PHTX,True,False,2006-12-13 02:45:00,12/13 10:40,12/13 02:54,34.0
162,14000,350,S26E90,9756,X3.4,NaN,360,2216,PHTX,True,False,2001-12-28 20:35:00,12/29 03:00,12/28 20:30,35.0
194,10000,2000,SE90b,10039,X3.3,NaN,360,1941,PHTX,True,False,2002-07-20 21:30:00,07/20 22:20,07/20 22:06,37.0
405,16000,700,N08E77,11748,X3.2,NaN,360,2625,PHTX,True,False,2013-05-14 01:16:00,05/14 02:35,05/14 01:25,39.0
202,5000,400,S02W81,10069,X3.1,NaN,360,1913,PHTX,True,False,2002-08-24 01:45:00,08/24 03:25,08/24 01:27,41.0
189,5000,175,N19W01,10030,M1.8,14,188,1300,PHTX,False,True,2002-07-15 21:15:00,07/16 05:00,07/15 21:30,42.0
404,16000,300,N11E85,11748,X2.8,NaN,360,1850,PHTX,True,False,2013-05-13 16:15:00,05/13 19:10,05/13 16:07,43.0
159,4500,750,SW90b,NaN,NaN,263,121,891,PHTX,False,False,2001-12-11 12:45:00,12/11 17:00,12/11 09:54,44.0
240,6000,400,N08W77,10488,X3.9,293,103,1420,PHTX,False,False,2003-11-03 10:00:00,11/03 12:30,11/03 10:06,47.0
19,14000,5000,S11W65,8210,X2.7,309,190,1099,PHTX,False,False,1998-05-06 08:25:00,05/06 08:35,05/06 08:29,48.0
286,3000,40,N15W05,10720,X2.6,NaN,360,2861,PHTX,True,False,2005-01-15 23:00:00,01/15 00:00,01/15 23:06,49.0
144,7000,30,S16E23,9632,X2.6,NaN,360,2402,PHTX,True,False,2001-09-24 10:45:00,09/25 20:00,09/24 10:30,50.0
239,3000,1500,N10W83,10488,X2.7,304,65,827,PHTX,False,False,2003-11-03 01:15:00,11/03 01:25,11/03 01:59,NaN
9,14000,7000,N17E63,8113,X2.6,98,91,441,PHTX,False,False,1997-11-27 13:30:00,11/27 14:00,11/27 13:56,NaN
278,14000,1000,N09W49,10696,X2.5,NaN,360,3387,PHTX,True,False,2004-11-10 02:25:00,11/10 03:40,11/10 02:26,NaN
101,14000,200,N22W07,9236,X2.3,NaN,360,1245,PHTX,True,False,2000-11-24 15:25:00,11/24 22:00,11/24 15:30,NaN
125,14000,100,S23W09,9415,X2.3,NaN,360,2411,PHTX,True,False,2001-04-10 05:24:00,04/10 24:00,04/10 05:30,NaN
73,14000,40,N20E18,9026,X2.3,NaN,360,1119,PHTX,True,False,2000-06-06 15:20:00,06/08 09:00,06/06 15:54,NaN
347,16000,400,S20W12,11158,X2.2,NaN,360,669,PHTX,True,False,2011-02-15 02:10:00,02/15 07:00,02/15 02:24,NaN
421,16000,200,S06E69,11882,X2.1,NaN,360,1081,PHTX,True,False,2013-10-25 15:08:00,10/25 22:32,10/25 15:12,NaN
362,16000,150,N14W18,11283,X2.1,NaN,360,575,PHTX,True,False,2011-09-06 22:30:00,09/07 15:40,09/06 23:05,NaN
7,14000,100,S14W33,8100,X2.1,NaN,360,785,PHTX,True,False,1997-11-04 06:00:00,11/05 04:30,11/04 06:10,NaN
320,14000,300,S13E47,10808,X2.1,NaN,360,1893,PHTX,True,False,2005-09-10 21:45:00,09/10 01:00,09/10 21:52,NaN
287,14000,30,N15W25,10720,X2.0,NaN,360,2094,PHTX,True,False,2005-01-17 09:25:00,01/17 16:00,01/17 09:30,NaN
127,14000,7000,S19W43,9415,X2.0,NaN,360,1184,PHTX,True,False,2001-04-12 10:20:00,04/12 10:40,04/12 10:31,NaN
276,14000,60,N09W17,10696,X2.0,NaN,360,1759,PHTX,True,False,2004-11-07 16:25:00,11/08 20:00,11/07 16:54,NaN
100,14000,100,N20W05,9236,X2.0,NaN,360,1289,PHTX,True,False,2000-11-24 05:10:00,11/24 15:00,11/24 05:30,NaN
104,6000,2000,N20W23,9236,X1.9,NaN,360,671,PHTX,True,False,2000-11-25 19:00:00,11/25 19:35,11/25 19:31,NaN

I matched using the year, month, and date because there is not many flares in the same day. Therefore, there is a good chance of finding the correct match for the give top 50 flare. Because of this, there were no duplicate matches. I did this by iterating through the first database and finding matches where the year, month, and day were the same. If there were any matches, I added the rank.